// dadda_reduced.sv � generated by generate_dadda_reduced.py
// Pruned Dadda tree: only logic contributing to z0/z1 bits [21:14].
// 45 instances (3 HA + 42 FA) vs 90 in dadda.sv.
module dadda_reduced
(
  input  logic [10 : 0] x,
  input  logic [10 : 0] y,
  output logic [21 : 0] z0,
  output logic [21 : 0] z1
);

  logic [10:0][10:0] P;

  logic [89 : 0] S;
  logic [89 : 0] C;

  // Partial products needed for bits [21:14]
  assign P[0][9] = x[0] & y[9];
  assign P[0][10] = x[0] & y[10];
  assign P[1][8] = x[1] & y[8];
  assign P[1][9] = x[1] & y[9];
  assign P[1][10] = x[1] & y[10];
  assign P[2][8] = x[2] & y[8];
  assign P[2][9] = x[2] & y[9];
  assign P[2][10] = x[2] & y[10];
  assign P[3][7] = x[3] & y[7];
  assign P[3][8] = x[3] & y[8];
  assign P[3][9] = x[3] & y[9];
  assign P[3][10] = x[3] & y[10];
  assign P[4][6] = x[4] & y[6];
  assign P[4][7] = x[4] & y[7];
  assign P[4][8] = x[4] & y[8];
  assign P[4][9] = x[4] & y[9];
  assign P[4][10] = x[4] & y[10];
  assign P[5][6] = x[5] & y[6];
  assign P[5][7] = x[5] & y[7];
  assign P[5][8] = x[5] & y[8];
  assign P[5][9] = x[5] & y[9];
  assign P[5][10] = x[5] & y[10];
  assign P[6][5] = x[6] & y[5];
  assign P[6][6] = x[6] & y[6];
  assign P[6][7] = x[6] & y[7];
  assign P[6][8] = x[6] & y[8];
  assign P[6][9] = x[6] & y[9];
  assign P[6][10] = x[6] & y[10];
  assign P[7][4] = x[7] & y[4];
  assign P[7][5] = x[7] & y[5];
  assign P[7][6] = x[7] & y[6];
  assign P[7][7] = x[7] & y[7];
  assign P[7][8] = x[7] & y[8];
  assign P[7][9] = x[7] & y[9];
  assign P[7][10] = x[7] & y[10];
  assign P[8][3] = x[8] & y[3];
  assign P[8][4] = x[8] & y[4];
  assign P[8][5] = x[8] & y[5];
  assign P[8][6] = x[8] & y[6];
  assign P[8][7] = x[8] & y[7];
  assign P[8][8] = x[8] & y[8];
  assign P[8][9] = x[8] & y[9];
  assign P[8][10] = x[8] & y[10];
  assign P[9][2] = x[9] & y[2];
  assign P[9][3] = x[9] & y[3];
  assign P[9][4] = x[9] & y[4];
  assign P[9][5] = x[9] & y[5];
  assign P[9][6] = x[9] & y[6];
  assign P[9][7] = x[9] & y[7];
  assign P[9][8] = x[9] & y[8];
  assign P[9][9] = x[9] & y[9];
  assign P[9][10] = x[9] & y[10];
  assign P[10][1] = x[10] & y[1];
  assign P[10][2] = x[10] & y[2];
  assign P[10][3] = x[10] & y[3];
  assign P[10][4] = x[10] & y[4];
  assign P[10][5] = x[10] & y[5];
  assign P[10][6] = x[10] & y[6];
  assign P[10][7] = x[10] & y[7];
  assign P[10][8] = x[10] & y[8];
  assign P[10][9] = x[10] & y[9];
  assign P[10][10] = x[10] & y[10];

  // Reduction tree: cone-of-influence of bits [21:14]
  ha HA_00000000 (P[0][9],P[1][8],S[0],C[0]);
  fa FA_00000001 (P[0][10],P[1][9],P[2][8],S[1],C[1]);
  ha HA_00000002 (P[3][7],P[4][6],S[2],C[2]);
  fa FA_00000003 (P[1][10],P[2][9],P[3][8],S[3],C[3]);
  ha HA_00000004 (P[4][7],P[5][6],S[4],C[4]);
  fa FA_00000005 (P[2][10],P[3][9],P[4][8],S[5],C[5]);
  fa FA_00000015 (S[1],C[0],S[2],S[15],C[15]);
  fa FA_00000018 (S[3],C[1],S[4],S[18],C[18]);
  fa FA_00000019 (C[2],P[6][5],P[7][4],S[19],C[19]);
  fa FA_00000020 (P[8][3],P[9][2],P[10][1],S[20],C[20]);
  fa FA_00000021 (S[5],C[3],C[4],S[21],C[21]);
  fa FA_00000022 (P[5][7],P[6][6],P[7][5],S[22],C[22]);
  fa FA_00000023 (P[8][4],P[9][3],P[10][2],S[23],C[23]);
  fa FA_00000024 (C[5],P[3][10],P[4][9],S[24],C[24]);
  fa FA_00000025 (P[5][8],P[6][7],P[7][6],S[25],C[25]);
  fa FA_00000026 (P[8][5],P[9][4],P[10][3],S[26],C[26]);
  fa FA_00000027 (P[4][10],P[5][9],P[6][8],S[27],C[27]);
  fa FA_00000028 (P[7][7],P[8][6],P[9][5],S[28],C[28]);
  fa FA_00000029 (P[5][10],P[6][9],P[7][8],S[29],C[29]);
  fa FA_00000043 (S[18],C[15],S[19],S[43],C[43]);
  fa FA_00000045 (S[21],C[18],S[22],S[45],C[45]);
  fa FA_00000046 (C[19],S[23],C[20],S[46],C[46]);
  fa FA_00000047 (S[24],C[21],S[25],S[47],C[47]);
  fa FA_00000048 (C[22],S[26],C[23],S[48],C[48]);
  fa FA_00000049 (S[27],C[24],S[28],S[49],C[49]);
  fa FA_00000050 (C[25],C[26],P[10][4],S[50],C[50]);
  fa FA_00000051 (S[29],C[27],C[28],S[51],C[51]);
  fa FA_00000052 (P[8][7],P[9][6],P[10][5],S[52],C[52]);
  fa FA_00000053 (C[29],P[6][10],P[7][9],S[53],C[53]);
  fa FA_00000054 (P[8][8],P[9][7],P[10][6],S[54],C[54]);
  fa FA_00000055 (P[7][10],P[8][9],P[9][8],S[55],C[55]);
  fa FA_00000065 (S[45],C[43],S[46],S[65],C[65]);
  fa FA_00000066 (S[47],C[45],S[48],S[66],C[66]);
  fa FA_00000067 (S[49],C[47],S[50],S[67],C[67]);
  fa FA_00000068 (S[51],C[49],S[52],S[68],C[68]);
  fa FA_00000069 (S[53],C[51],S[54],S[69],C[69]);
  fa FA_00000070 (S[55],C[53],C[54],S[70],C[70]);
  fa FA_00000071 (C[55],P[8][10],P[9][9],S[71],C[71]);
  fa FA_00000083 (S[66],C[65],C[46],S[83],C[83]);
  fa FA_00000084 (S[67],C[66],C[48],S[84],C[84]);
  fa FA_00000085 (S[68],C[67],C[50],S[85],C[85]);
  fa FA_00000086 (S[69],C[68],C[52],S[86],C[86]);
  fa FA_00000087 (S[70],C[69],P[10][7],S[87],C[87]);
  fa FA_00000088 (S[71],C[70],P[10][8],S[88],C[88]);
  fa FA_00000089 (C[71],P[9][10],P[10][9],S[89],C[89]);

  // Output assignments (bits outside [21:14] driven to 0)
  assign z0[0] = 1'b0;
  assign z0[1] = 1'b0;
  assign z0[2] = 1'b0;
  assign z0[3] = 1'b0;
  assign z0[4] = 1'b0;
  assign z0[5] = 1'b0;
  assign z0[6] = 1'b0;
  assign z0[7] = 1'b0;
  assign z0[8] = 1'b0;
  assign z0[9] = 1'b0;
  assign z0[10] = 1'b0;
  assign z0[11] = 1'b0;
  assign z0[12] = 1'b0;
  assign z0[13] = 1'b0;
  assign z0[14] = S[84];
  assign z0[15] = S[85];
  assign z0[16] = S[86];
  assign z0[17] = S[87];
  assign z0[18] = S[88];
  assign z0[19] = S[89];
  assign z0[20] = C[89];
  assign z0[21] = 1'b0;
  assign z1[0] = 1'b0;
  assign z1[1] = 1'b0;
  assign z1[2] = 1'b0;
  assign z1[3] = 1'b0;
  assign z1[4] = 1'b0;
  assign z1[5] = 1'b0;
  assign z1[6] = 1'b0;
  assign z1[7] = 1'b0;
  assign z1[8] = 1'b0;
  assign z1[9] = 1'b0;
  assign z1[10] = 1'b0;
  assign z1[11] = 1'b0;
  assign z1[12] = 1'b0;
  assign z1[13] = 1'b0;
  assign z1[14] = C[83];
  assign z1[15] = C[84];
  assign z1[16] = C[85];
  assign z1[17] = C[86];
  assign z1[18] = C[87];
  assign z1[19] = C[88];
  assign z1[20] = P[10][10];
  assign z1[21] = 1'b0;

endmodule
