###############################################################################
# Created by write_sdc
###############################################################################
current_design gemm_top
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 14.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty 0.2500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[0]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[10]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[11]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[12]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[13]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[14]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[15]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[16]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[17]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[18]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[19]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[1]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[20]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[21]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[22]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[23]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[24]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[25]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[26]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[27]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[28]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[29]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[2]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[30]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[31]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[3]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[4]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[5]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[6]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[7]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[8]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_DATA[9]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_LEN[0]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_LEN[1]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_LEN[2]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {A_LEN[3]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[0]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[10]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[11]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[12]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[13]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[14]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[15]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[1]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[2]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[3]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[4]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[5]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[6]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[7]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[8]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS[9]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS_NEW}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS_VLD}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {DATA_VLD}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {K_LEN[0]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {K_LEN[1]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {K_LEN[2]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {K_LEN[3]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {METADATA_VLD}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {RELU_EN}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[0]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[10]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[11]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[12]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[13]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[14]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[15]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[1]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[2]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[3]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[4]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[5]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[6]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[7]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[8]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE[9]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE_VLD}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {TILE_LAST}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {TILE_START}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[0]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[10]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[11]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[12]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[13]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[14]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[15]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[16]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[17]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[18]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[19]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[1]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[20]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[21]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[22]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[23]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[24]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[25]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[26]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[27]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[28]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[29]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[2]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[30]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[31]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[3]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[4]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[5]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[6]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[7]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[8]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_DATA[9]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_LEN[0]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_LEN[1]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_LEN[2]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {W_LEN[3]}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_RDY}]
set_input_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {rst_n}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {BIAS_RDY}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {DATA_RDY}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {METADATA_RDY}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {SCALE_RDY}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {TILE_DONE}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[0]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[10]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[11]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[12]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[13]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[14]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[15]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[16]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[17]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[18]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[19]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[1]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[20]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[21]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[22]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[23]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[24]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[25]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[26]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[27]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[28]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[29]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[2]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[30]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[31]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[3]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[4]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[5]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[6]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[7]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[8]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_OUT[9]}]
set_output_delay 2.8000 -clock [get_clocks {clk}] -add_delay [get_ports {Y_VLD}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0334 [get_ports {BIAS_RDY}]
set_load -pin_load 0.0334 [get_ports {DATA_RDY}]
set_load -pin_load 0.0334 [get_ports {METADATA_RDY}]
set_load -pin_load 0.0334 [get_ports {SCALE_RDY}]
set_load -pin_load 0.0334 [get_ports {TILE_DONE}]
set_load -pin_load 0.0334 [get_ports {Y_VLD}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[31]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[30]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[29]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[28]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[27]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[26]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[25]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[24]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[23]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[22]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[21]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[20]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[19]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[18]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[17]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[16]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[15]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[14]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[13]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[12]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[11]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[10]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[9]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[8]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[7]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[6]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[5]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[4]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[3]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[2]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[1]}]
set_load -pin_load 0.0334 [get_ports {Y_OUT[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS_NEW}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS_VLD}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {DATA_VLD}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {METADATA_VLD}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {RELU_EN}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE_VLD}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {TILE_LAST}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {TILE_START}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {Y_RDY}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst_n}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_DATA[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_LEN[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_LEN[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_LEN[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {A_LEN[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {BIAS[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {K_LEN[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {K_LEN[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {K_LEN[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {K_LEN[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {SCALE[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[31]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[30]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[29]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[28]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[27]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[26]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[25]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[24]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[23]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[22]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[21]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[20]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[19]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[18]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[17]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[16]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[15]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[14]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[13]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[12]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[11]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[10]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[9]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[8]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[7]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[6]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[5]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[4]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_DATA[0]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_LEN[3]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_LEN[2]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_LEN[1]}]
set_driving_cell -lib_cell sky130_fd_sc_hd__inv_2 -pin {Y} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {W_LEN[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_transition 0.7500 [current_design]
set_max_capacitance 0.2000 [current_design]
set_max_fanout 10.0000 [current_design]
